Make signature generation compatible with OTP24
gabrielpra1/deribit-elixir pull request #1
Opened 2021-08-31 11:41 UTC by icostan

:crypto.hmac(:sha256, ...) was removed in OTP24 and has to be replaced with :crypto.mac(:hmac, :sha256, ...)

2021-08-31 13:05 UTC, gabrielpra1 requested changes

2021-08-31 13:05 UTC, gabrielpra1 commented on lib/deribit_http.ex
> +    # signature = :crypto.hmac(:sha256, client_secret, text) |> Base.encode16()
Hey, thanks for the PR!

The problem with this approach is that it would break for everyone using OTP < 22.

A way to make this work for both cases would be to define our `hmac` function like this:

```elixir
  # TODO: remove when we require OTP 22.1
  if Code.ensure_loaded?(:crypto) and function_exported?(:crypto, :mac, 4) do
    defp hmac(digest, key, data), do: :crypto.mac(:hmac, digest, key, data)
  else
    defp hmac(digest, key, data), do: :crypto.hmac(digest, key, data)
  end
```

2021-09-02 07:04 UTC, icostan commented on lib/deribit_http.ex
> +    # signature = :crypto.hmac(:sha256, client_secret, text) |> Base.encode16()
I totally agree, my bad, it breaks older versions, I should have changed the dependencies as well and require > OTP22.

On the other hand I am not a big fan of changing code to preserve backward compatibility, I usually do it by tagging the old version, commit all changes, bump major and release new incompatible version, it's opinionated, I know  :)

Anyway, I'll do it either way, just let me know which variant you prefer.

2021-09-06 08:31 UTC, icostan commented on lib/deribit_http.ex
> +    # signature = :crypto.hmac(:sha256, client_secret, text) |> Base.encode16()
I added the private 'hmac' function but since there is no test I am not able to check out anything. Sorry, I don't do manual work.

If you think it looks good then quash the commits, otherwise just discard the PR.

2026-03-18 06:01 UTC, closed without merging